title: SkillSpike
description: Elevate Your IT Skills. Accelerate Your Career.
baseurl: "" 
url: "https://skillspike.info"
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
